# <center>Анализ эффективности рекламы</center>

Иморт библиотек и запись файлов для анализа

In [31]:
import pandas as pd
import numpy as np

In [ ]:
spend = pd.read_csv('./in_data_p.csv')
downloads = pd.read_csv('./in_data_a.csv')

<b>Анализ файлов</b>

In [3]:
spend.rename(columns={'date': 'Date'}, inplace=True)

In [4]:
spend.head(10)

         Date  campaign     ad_id  spend
0  2019-02-11  11484480  32631604  49.18
1  2019-02-11  11484485  32631612  33.19
2  2019-02-11  11484611  32631778   2.52
3  2019-02-11  11487692  32636729   7.08
4  2019-02-11  11487692  32636730   7.47
5  2019-02-11  11487692  32636731   1.18
6  2019-02-11  11487692  32636732   1.75
7  2019-02-11  11487692  32636733   3.97
8  2019-02-11  11487738  32636798  42.89
9  2019-02-11  11487745  32636813  61.84

In [5]:
downloads = downloads.sort_values('Date')

In [6]:
downloads.head(10)

             Date Campaign    id     ad_id       os  Installs   app
42742  2019-02-11       RU  2260  35101956      ios       0.0  auto
4227   2019-02-11      MSK  2260  36285054  android       0.0  real
4228   2019-02-11      MSK  2260  36285055  android       0.0  real
4229   2019-02-11      MSK  2260  36285056  android       0.0  real
4230   2019-02-11      MSK  2260  36285057  android       0.0  real
4231   2019-02-11      MSK  2260  36285074  android       0.0  real
4232   2019-02-11      MSK  2260  36285075  android       0.0  real
4233   2019-02-11      MSK  2260  36285075  windows       0.0  real
4234   2019-02-11      MSK  2260  36285076  android       0.0  real
4235   2019-02-11      MSK  2260  36285077  android       0.0  real

In [7]:
spend.describe()

           campaign         ad_id         spend
count  1.970400e+04  1.970400e+04  19704.000000
mean   1.392558e+07  3.633183e+07     83.800369
std    1.077161e+06  1.665790e+06    533.373845
min    1.148448e+07  3.263160e+07      0.000000
25%    1.314904e+07  3.514996e+07      0.000000
50%    1.437910e+07  3.698382e+07      2.780000
75%    1.472733e+07  3.761116e+07     24.995000
max    1.526131e+07  3.851634e+07  18508.490000

In [8]:
downloads.describe()

                 id         ad_id      Installs
count  55869.000000  5.586900e+04  55869.000000
mean    1998.147470  3.599211e+07      0.331561
std      409.537097  1.917174e+06      3.604002
min     1190.000000  3.260070e+07      0.000000
25%     1957.000000  3.429681e+07      0.000000
50%     2260.000000  3.638553e+07      0.000000
75%     2260.000000  3.763177e+07      0.000000
max     2260.000000  3.851634e+07    171.000000

Две таблицы можно соединить по полям Date и ad_id

<b>Соединяем с помощью full join</b>

In [13]:
all_data = spend.merge(downloads, on=['Date', 'ad_id'], how='outer')

In [14]:
all_data

,Date,campaign,ad_id,spend,Campaign,id,os,Installs,app
0,2019-02-11,11484480.0,32631604,49.18,SPB,2260.0,android,1.0,real
1,2019-02-11,11484485.0,32631612,33.19,SPB,2260.0,android,0.0,real
2,2019-02-11,11484611.0,32631778,2.52,NaN,NaN,NaN,NaN,NaN
3,2019-02-11,11487692.0,32636729,7.08,SPB,2260.0,android,0.0,real
4,2019-02-11,11487692.0,32636730,7.47,SPB,2260.0,android,0.0,real
5,2019-02-11,11487692.0,32636731,1.18,SPB,2260.0,android,0.0,real
6,2019-02-11,11487692.0,32636732,1.75,SPB,2260.0,android,0.0,real
7,2019-02-11,11487692.0,32636733,3.97,SPB,2260.0,android,0.0,real
8,2019-02-11,11487738.0,32636798,42.89,NaN,NaN,NaN,NaN,NaN
9,2019-02-11,11487745.0,32636813,61.84,NaN,NaN,NaN,NaN,NaN
10,2019-02-11,11488819.0,32638585,0.00,SPB,2260.0,android,0.0,real
11,2019-02-11,11488819.0,32638588,0.00,SPB,2260.0,android,0.0,real
12,2019-02-11,11488819.0,32638589,0.00,SPB,2260.0,android,0.0,real
13,2019-02-11,11488831.0,32638613,0.00,NaN,NaN,NaN,NaN,NaN
14,2019-02-11,11488835.0,32638620,230.00,NaN,NaN,NaN,NaN,NaN
15,2019-02-11,11491346.0,32641692,0.00,RU,2260.0,android,0.0,auto
16,2019-02-11,11491346.0,32641695,0.00,RU,2260.0,android,0.0,auto
17,2019-02-11,11491395.0,32641769,0.00,RU,2260.0,android,0.0,auto
18,2019-02-11,11491395.0,32641771,0.00,RU,2260.0,android,0.0,auto
19,2019-02-11,11491429.0,32641825,0.00,RU,2260.0,android,0.0,auto
20,2019-02-11,11506887.0,32663046,0.00,RU,2260.0,ios,0.0,auto
21,2019-02-11,11506887.0,32663048,0.00,RU,2260.0,ios,0.0,auto
22,2019-02-11,11517044.0,32676829,16.45,MSK_SPB,2260.0,android,0.0,auto
23,2019-02-11,11531497.0,32701506,350.50,SPB,2260.0,android,5.0,real
24,2019-02-11,11531515.0,32701525,187.91,SPB,2260.0,android,1.0,real
25,2019-02-11,11531515.0,32701525,187.91,SPB,2260.0,server,0.0,real
26,2019-02-11,11531547.0,32701582,20.29,NaN,NaN,NaN,NaN,NaN
27,2019-02-11,11531557.0,32701599,24.61,NaN,NaN,NaN,NaN,NaN
28,2019-02-11,11532401.0,32702811,543.23,SPB,2260.0,android,6.0,real
29,2019-02-11,11532401.0,32702811,543.23,SPB,2260.0,server,0.0,real
...,...,...,...,...,...,...,...,...,...
60118,2019-03-11,NaN,37505598,NaN,RU,2260.0,android,0.0,auto
60119,2019-03-11,NaN,37505599,NaN,RU,2260.0,android,0.0,auto
60120,2019-03-11,NaN,36329587,NaN,RU,2260.0,android,0.0,auto
60121,2019-03-11,NaN,36329586,NaN,RU,2260.0,android,0.0,auto
60122,2019-03-11,NaN,36329585,NaN,RU,2260.0,android,0.0,auto
60123,2019-03-11,NaN,36329584,NaN,RU,2260.0,android,0.0,auto
60124,2019-03-11,NaN,35149959,NaN,RU,2260.0,android,0.0,auto
60125,2019-03-11,NaN,35150146,NaN,RU,2260.0,android,0.0,auto
60126,2019-03-11,NaN,35150147,NaN,RU,2260.0,android,0.0,auto
60127,2019-03-11,NaN,36285464,NaN,RU,2260.0,android,0.0,auto
60128,2019-03-11,NaN,36285465,NaN,RU,2260.0,android,0.0,auto
60129,2019-03-11,NaN,36285466,NaN,RU,2260.0,android,0.0,auto
60130,2019-03-11,NaN,36285467,NaN,RU,2260.0,android,0.0,auto
60131,2019-03-11,NaN,36285468,NaN,RU,2260.0,android,0.0,auto
60132,2019-03-11,NaN,36285647,NaN,RU,2260.0,android,0.0,auto
60133,2019-03-11,NaN,37611047,NaN,RU,2260.0,android,0.0,auto
60134,2019-03-11,NaN,36285648,NaN,RU,2260.0,android,0.0,auto
60135,2019-03-11,NaN,36285650,NaN,RU,2260.0,android,0.0,auto
60136,2019-03-11,NaN,36285651,NaN,RU,2260.0,android,0.0,auto
60137,2019-03-11,NaN,36285652,NaN,RU,2260.0,android,0.0,auto
60138,2019-03-11,NaN,36285958,NaN,RU,2260.0,android,0.0,auto
60139,2019-03-11,NaN,36285961,NaN,RU,2260.0,android,0.0,auto
60140,2019-03-11,NaN,36329142,NaN,RU,2260.0,android,0.0,auto
60141,2019-03-11,NaN,36329546,NaN,RU,2260.0,android,0.0,auto
60142,2019-03-11,NaN,36329547,NaN,RU,2260.0,android,0.0,auto
60143,2019-03-11,NaN,36329570,NaN,RU,2260.0,android,0.0,auto
60144,2019-03-11,NaN,36329571,NaN,RU,2260.0,android,0.0,auto
60145,2019-03-11,NaN,36329583,NaN,RU,2260.0,android,0.0,auto
60146,2019-03-11,NaN,36285649,NaN,RU,2260.0,android,0.0,auto
60147,2019-03-11,NaN,37367661,NaN,SPB,2260.0,ios,0.0,auto

Появляется много пустот, которые уберутся при группировке

<b>Делаем итоговую таблицу out суммируя траты и установки</b>

In [47]:
out = all_data.groupby(['Date', 'app', 'Campaign','os']).agg({'spend': 'sum', 'Installs': 'sum'})

<b>Создаем столбец, показывающий эффективность рекламы</b>

In [49]:
out['cpi'] = out['spend']/out['Installs']

Заменяем пустые значения и бесконечности образовавшиеся вследствии деления на ноль(скачиваний)

In [50]:
out['cpi'].replace([np.inf, np.NaN], 0, inplace=True)

In [55]:
out

                                     spend  Installs         cpi
Date       app  Campaign os
2019-02-11 auto MSK_SPB  android    492.87       4.0  123.217500
                         ios        132.42       2.0   66.210000
                RU       android  13677.70     187.0   73.142781
                         ios       1632.38      21.0   77.732381
                         macos        0.00       0.0    0.000000
                         server    8227.13       0.0    0.000000
                         windows      0.00       0.0    0.000000
                RU_comm  android      0.00       0.0    0.000000
                         ios          0.00       0.0    0.000000
                SPB      android    251.29       4.0   62.822500
                         ios         35.67       0.0    0.000000
                         windows      0.00       0.0    0.000000
           real MSK      android   3581.05      70.0   51.157857
                         server    1518.23       0.0    0.000000
                         windows      0.00       0.0    0.000000
                SPB      android  12540.30      90.0  139.336667
                         ios          0.00       0.0    0.000000
                         macos        0.00       0.0    0.000000
                         server    9734.84       0.0    0.000000
2019-02-12 auto MSK_SPB  android    529.90       6.0   88.316667
                         ios         60.60       1.0   60.600000
                RU       android  18405.64     221.0   83.283439
                         ios       1220.84      13.0   93.910769
                         server   10638.07       0.0    0.000000
                         unknown      0.00       0.0    0.000000
                         windows    648.40       0.0    0.000000
                RU_comm  android      0.00       0.0    0.000000
                         ios          0.00       0.0    0.000000
                SPB      android    306.23       4.0   76.557500
                         ios         28.70       0.0    0.000000
...                                    ...       ...         ...
2019-03-10 auto RU       ios       2317.76      38.0   60.993684
                         server   15754.30       0.0    0.000000
                         windows      0.00       0.0    0.000000
                RU_comm  android      0.00       0.0    0.000000
                         ios          0.00       0.0    0.000000
                SPB      android    117.16       0.0    0.000000
                         ios          0.00       0.0    0.000000
           real MSK      android   7782.66     166.0   46.883494
                         ios       1469.67      18.0   81.648333
                         server    5219.73       0.0    0.000000
                         windows      0.00       0.0    0.000000
                SPB      android   6251.68      52.0  120.224615
                         ios       1340.00      13.0  103.076923
                         server    3917.26       0.0    0.000000
2019-03-11 auto MSK_SPB  android    694.56       8.0   86.820000
                         ios          7.43       1.0    7.430000
                         server      65.31       0.0    0.000000
                RU       android  10552.85     162.0   65.141049
                         ios        743.39       9.0   82.598889
                         server    6498.10       0.0    0.000000
                RU_comm  android      0.00       0.0    0.000000
                         ios          0.00       0.0    0.000000
                SPB      android    194.10       1.0  194.100000
                         ios          0.00       0.0    0.000000
           real MSK      android   3659.61      78.0   46.918077
                         ios        284.32       9.0   31.591111
                         server    1998.58       0.0    0.000000
                SPB      android   2314.06      27.0   85.705926
                         ios        106.30       3.0   35.433333
                         server    1387.22       0.0    0.000000

[527 rows x 3 columns]

<b>Записываем в файл</b>

In [57]:
out.to_csv('./out.csv', sep='\t')